version: "0.0.1" 
services: 
  redis: 
    container_name: redis 
    hostname: redis 
    image: redis 
    ports: 
      - "6379:6379"

  redis-commander: 
    container_name: redis-container
    hostname: redis-container 
    image: rediscontainer/redis-container:latest 
    restart: always 
    environment: 
      - REDIS_HOSTS=local:redis:6379 
    ports: 
      - "8081:8081"